### ISSUE TITLE
Update readme to include RedHat YAML extension dependency

### ISSUE THREAD

**Issue by SChubb** [engineer-taro/aws-sam-snippets-VSCode#1]
Hi,

This is a really useful extension that has saved me a bunch of time - and especially as I can never remember the syntax for things like SAM.

However, it took me ages to realise you had to also have the RedHat YAML extension installed for this to work - would help others if this was included in the readme

Thanks for your work on this
Simon

**Comment by engineer-taro** [comment]
@SChubb
Hi Simon,

Thank you for your comments.
It is very encouraging to know that you are using it.

But sorry, I also checked the behavior in my local environment, and it seems to work fine without the RedHat YAML extension. I've attached a video of the behavior.

The video shows how it works with the RedHat YAML extension disabled.
![7ed2971d0aac120b95bf9884efb91be7 (1)](https://user-images.githubusercontent.com/81571628/154498203-abecee67-8773-490a-b1b4-e441800ee6f5.gif)

Can you please let me know the behavior that is causing the problem?


Taro

**Comment by SChubb** [comment]
Hi Taro,

I installed the SAM Snippets extension on VS Code. Then in either a new or existing yaml file, when typing sam nothing would happen. Restarting VS Code didn't work either.

I could only get it to appear after uninstalling the SAM snippets extension, installing the RedHat YAML support, then re-installing the sam snippets extension.

Thanks
Simon
________________________________

**Comment by engineer-taro** [comment]
@SChubb
Simon,

Thank you for your report.
We have added a note to the readme stating that the reported issue occurs and how to work around it!

https://github.com/engineer-taro/aws-sam-snippets-VSCode/commit/0ccad6796b09ab76600d9b375ce151be5ef2fdb2
